
# Cocoapod
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '11.0'
inhibit_all_warnings!


def shared_pods
	pod 'SnapKit', '~> 4.0'
	pod 'SwiftLint'
	pod 'SwiftyVIPER', :path => '../'
end

target 'SwiftyVIPERExample' do
	shared_pods
end

target 'SwiftyVIPERExampleTests' do
	shared_pods
end
